CREATE TABLE users (
    id UUID NOT NULL,
    provider VARCHAR(20) NOT NULL,
    provider_id VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_provider_provider_id UNIQUE (provider, provider_id)
);

CREATE TABLE session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id UUID NOT NULL,
    device_id VARCHAR(255) NOT NULL,
    device_name VARCHAR(255) NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    last_accessed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_session PRIMARY KEY (id),
    CONSTRAINT uk_session_device_id UNIQUE (device_id),
    CONSTRAINT fk_session_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE refresh_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    session_id BIGINT,
    token VARCHAR(512) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_refresh_token PRIMARY KEY (id),
    CONSTRAINT uk_refresh_token_token UNIQUE (token),
    CONSTRAINT fk_refresh_token_session FOREIGN KEY (session_id) REFERENCES session (id)
);

CREATE TABLE subscription_product (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    plan_tier VARCHAR(10) NOT NULL,
    description VARCHAR(500),
    features JSONB,
    is_active BOOLEAN NOT NULL,
    max_questions INTEGER NOT NULL,
    weekly_interview_limit INTEGER NOT NULL,
    weekly_improvement_practice_limit INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_subscription_product PRIMARY KEY (id)
);

CREATE TABLE subscription_plan (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id INTEGER NOT NULL,
    price NUMERIC(19,4) NOT NULL,
    currency VARCHAR(10) NOT NULL,
    billing_cycle VARCHAR(20) NOT NULL,
    CONSTRAINT pk_subscription_plan PRIMARY KEY (id),
    CONSTRAINT uk_product_billing_cycle_currency UNIQUE (product_id, billing_cycle, currency),
    CONSTRAINT fk_subscription_plan_product FOREIGN KEY (product_id) REFERENCES subscription_product (id)
);

CREATE TABLE subscription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id UUID NOT NULL,
    plan_id INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    started_at TIMESTAMP,
    current_period_start TIMESTAMP,
    current_period_end TIMESTAMP,
    cancelled_at TIMESTAMP,
    current_payment_schedule_id VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_subscription PRIMARY KEY (id),
    CONSTRAINT fk_subscription_plan FOREIGN KEY (plan_id) REFERENCES subscription_plan (id)
);

CREATE TABLE payment_method (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id UUID NOT NULL,
    billing_key VARCHAR(255) NOT NULL,
    card_number VARCHAR(20),
    card_brand VARCHAR(20),
    is_active BOOLEAN NOT NULL,
    is_default BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_payment_method PRIMARY KEY (id),
    CONSTRAINT fk_payment_method_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE invoice (
    id VARCHAR(255) NOT NULL,
    subscription_id BIGINT NOT NULL,
    amount NUMERIC(19,4) NOT NULL,
    currency VARCHAR(10) NOT NULL,
    status VARCHAR(20) NOT NULL,
    period_start TIMESTAMP NOT NULL,
    period_end TIMESTAMP NOT NULL,
    paid_at TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_invoice PRIMARY KEY (id),
    CONSTRAINT fk_invoice_subscription FOREIGN KEY (subscription_id) REFERENCES subscription (id)
);

CREATE TABLE payment (
    id VARCHAR(255) NOT NULL,
    invoice_id VARCHAR(255) NOT NULL,
    amount NUMERIC(19,4) NOT NULL,
    currency VARCHAR(10) NOT NULL,
    status VARCHAR(20) NOT NULL,
    payment_method VARCHAR(20),
    paid_at TIMESTAMP,
    failed_reason VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_payment PRIMARY KEY (id),
    CONSTRAINT fk_payment_invoice FOREIGN KEY (invoice_id) REFERENCES invoice (id)
);

CREATE TABLE outbox_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    aggregate_type VARCHAR(50) NOT NULL,
    aggregate_id BIGINT NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    payload TEXT NOT NULL,
    status VARCHAR(20) NOT NULL,
    retry_count INTEGER NOT NULL,
    fail_reason VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_outbox_event PRIMARY KEY (id)
);

CREATE TABLE quota_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id UUID NOT NULL,
    quota_type VARCHAR(30) NOT NULL,
    period_start DATE NOT NULL,
    used_count INTEGER NOT NULL,
    CONSTRAINT pk_quota_usage PRIMARY KEY (id),
    CONSTRAINT uk_quota_usage_user_type_period UNIQUE (user_id, quota_type, period_start)
);

CREATE TABLE interview_session (
    id UUID NOT NULL,
    user_id UUID NOT NULL,
    position VARCHAR(100) NOT NULL,
    self_introduction TEXT NOT NULL,
    experience_level VARCHAR(20) NOT NULL,
    interview_type VARCHAR(20) NOT NULL,
    total_questions INTEGER NOT NULL,
    current_question_number INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    ended_at TIMESTAMP WITH TIME ZONE,
    first_question_keyword VARCHAR(100),
    feedback_status VARCHAR(20),
    fail_reason VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_interview_session PRIMARY KEY (id),
    CONSTRAINT fk_interview_session_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE interview_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    session_id UUID NOT NULL,
    role VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    question_number INTEGER,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_interview_message PRIMARY KEY (id),
    CONSTRAINT fk_interview_message_session FOREIGN KEY (session_id) REFERENCES interview_session (id)
);

CREATE TABLE interview_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    session_id UUID NOT NULL,
    overall_score INTEGER NOT NULL,
    expert_feedbacks JSONB NOT NULL,
    strengths TEXT NOT NULL,
    improvements TEXT NOT NULL,
    detailed_analysis TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_interview_feedback PRIMARY KEY (id),
    CONSTRAINT uk_interview_feedback_session UNIQUE (session_id),
    CONSTRAINT fk_interview_feedback_session FOREIGN KEY (session_id) REFERENCES interview_session (id)
);

INSERT INTO subscription_product (name, description, features, plan_tier, is_active, max_questions, weekly_interview_limit, weekly_improvement_practice_limit, created_at, updated_at) VALUES
    ('Free', 'AI 면접 연습을 가볍게 체험해보세요', CAST('["AI 면접 연습 주 1회", "AI 기본 피드백 제공", "면접 결과 요약 제공", "면접 기록 7일 보관"]' AS JSONB), 'FREE', true, 3, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Basic', 'AI와 함께 면접을 준비하는 가장 기본적인 플랜', CAST('["AI 면접 연습 주 4회", "AI 상세 피드백 제공", "면접 결과 비교 및 히스토리 관리", "면접 기록 무제한 보관", "음성 기반 AI 인터뷰 지원"]' AS JSONB), 'BASIC', true, 5, 4, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Pro', 'AI 분석을 통해 면접 실력을 체계적으로 개선하세요', CAST('["AI 면접 연습 주 10회", "AI 심층 분석 리포트 제공", "개선 연습 주 4회", "개인 맞춤형 AI 피드백", "면접 결과 추이 분석", "음성 기반 AI 인터뷰 지원"]' AS JSONB), 'PRO', true, 7, 10, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO subscription_plan (product_id, price, currency, billing_cycle)
SELECT id, 0, 'KRW', 'MONTHLY' FROM subscription_product WHERE plan_tier = 'FREE';
INSERT INTO subscription_plan (product_id, price, currency, billing_cycle)
SELECT id, 5900, 'KRW', 'MONTHLY' FROM subscription_product WHERE plan_tier = 'BASIC';
INSERT INTO subscription_plan (product_id, price, currency, billing_cycle)
SELECT id, 9900, 'KRW', 'MONTHLY' FROM subscription_product WHERE plan_tier = 'PRO';
